# : Manager [[[

[mgr]
cwd = { fg = "#e3e2e9" }

# Tab
tab_active = { fg = "#192e60", bg = "#b3c5ff", bold = true }
tab_inactive = { fg = "#314578", bg = "#dae1ff" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#5a3d58", bg = "#5a3d58" }
marker_cut = { fg = "#5a3d58", bg = "#5a3d58" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e1bbdc", bg = "#e1bbdc" }

# Count
count_copied = { fg = "#ffd6f9", bg = "#5a3d58" }
count_cut = { fg = "#ffd6f9", bg = "#5a3d58" }
count_selected = { fg = "#192e60", bg = "#e1bbdc" }

# Border
border_style  = { fg = "#b3c5ff" }

# : ]]]


# : Status [[[

[status]
separator_style = { bg = "#192e60", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#b3c5ff", fg = "#192e60", bold = true }
normal_alt  = { bg = "#45464f", fg = "#c5c6d0" }

# Select mode
select_main = { bg = "#c1c6dd", fg = "#2a3042", bold = true }
select_alt  = { bg = "#45464f", fg = "#c5c6d0" }

# Unset mode
unset_main = { bg = "#e1bbdc", fg = "#422741", bold = true }
unset_alt  = { bg = "#45464f", fg = "#c5c6d0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#b3c5ff", bg = "#121318" }
progress_error = { fg = "#ffb4ab", bg = "#121318" }

# Permissions
permissions_t = { fg = "#c1c6dd" }
permissions_w = { fg = "#e1bbdc" }
permissions_x = { fg = "#ffb4ab" }
permissions_r = { fg = "#5a3d58" }
permissions_s = { fg = "#314578" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#b3c5ff" }
active = { fg = "#e1bbdc", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#b3c5ff" }
value = { fg = "#e3e2e9" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#b3c5ff", bold = true, bg = "#121318" }
inactive = { fg = "#c1c6dd", bg = "#121318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#b3c5ff", bg = "#192e60" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#b3c5ff" }
title = {}
hovered = { fg = "#5a3d58", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#121318" }
cand = { fg = "#b3c5ff" }
rest = { fg = "#192e60" }
desc = { fg = "#e3e2e9" }
separator = " â–¶ "
separator_style = { fg = "#e3e2e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e3e2e9" }
run = { fg = "#e3e2e9" }
footer = { fg = "#2a3042", bg = "#c1c6dd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e1bbdc" }
title_warn = { fg = "#b3c5ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e3e2e9" },
    { name = "*/", fg = "#b3c5ff" },
]

# : ]]]
